# Generated by Django 3.2.9 on 2021-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
    ]
