# Generated by Django 3.2.9 on 2021-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_customer_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField(default=0)),
                ('avg_polarity', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('avg_subjectivity', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('no_verified', models.IntegerField(default=0)),
                ('no_protected', models.IntegerField(default=0)),
                ('avg_favorites', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('avg_tweets', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('avg_account_tweets', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('avg_followers', models.IntegerField(default=0)),
            ],
        ),
    ]
