# Generated by Django 3.2.9 on 2021-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='customers',
            field=models.IntegerField(default=0),
        ),
    ]
